/*
 * projects.js — 作品集数据（数据驱动，新增/修改项目只改此文件）
 * 字段说明：
 *   name/tagline/desc/depth/value/businessValue 均含 zh / en 双语
 *   cat     分类 key，见下方 CATEGORIES
 *   tech    技术栈标签数组
 *   repo     GitHub 地址（空字符串表示尚未开源）
 *   demo    在线演示地址（可选）
 *   status   open=已开源 | soon=即将开源 | deploy=私有化部署
 *   original true=本人原创 | false=基于第三方二次开发/部署
 *   motif   缩略图样式
 *   accent  主题强调色（十六进制）
 */

const CATEGORIES = {
  'ai-dev':    { zh: 'AI 开发工具',   en: 'AI Dev Tools' },
  'ai-app':    { zh: 'AI 应用',        en: 'AI Applications' },
  'infra':     { zh: 'AI 基础设施',   en: 'AI Infrastructure' },
  'industry':  { zh: '行业系统',       en: 'Industry Systems' },
  'fintech':   { zh: '金融量化',       en: 'Quant Finance' },
  'efficiency':{ zh: '效率与产品',     en: 'Efficiency & Products' },
};

const PROJECTS = [
  {
    id: 'aide',
    name: { zh: 'AIDE · AI 代码质检器', en: 'AIDE · AI Code Inspector' },
    tagline: { zh: '零配置、默认零 LLM 成本的 AI 生成代码体检', en: 'Zero-config, zero-LLM-cost audit for AI-generated code' },
    cat: 'ai-dev',
    tech: ['Node.js', 'TypeScript', 'AST', '正则引擎', 'CI 友好'],
    desc: {
      zh: '面向 AI 生成代码的静态质检 CLI：本地离线扫描幻觉包、桩函数、硬编码、安全隐患等。',
      en: 'A static CLI that audits AI-generated code locally for hallucinated packages, stubs, hardcoded secrets and more.',
    },
    depth: {
      zh: ['11 个稳定检测器（含 5 个预览），覆盖包幻觉/API 幻觉/桩函数/资源泄漏/安全等',
           '支持 13 种语言（Python/TS/JS/Java/Go 深度支持，Rust/Ruby/PHP 基础支持）',
           '纯本地扫描：默认 0 token 消耗，可选 LLM 辅助降误报（先本地预筛 40–60%）',
           'CI 友好：--exit-code、JSON/supervisor 输出、--offline 模式'],
      en: ['11 stable detectors (5 preview) for package/API hallucination, stubs, leaks, security',
           '13 languages (deep: Python/TS/JS/Java/Go; basic: Rust/Ruby/PHP)',
           'Pure local scan: 0 token by default; optional LLM pre-filter (40–60% local)',
           'CI-ready: --exit-code, JSON/supervisor output, --offline'],
    },
    value: {
      zh: '让「AI 写代码」可落地到生产：在合并前自动捕获最典型的 AI 幻觉与安全隐患，省去大量人工 code review。',
      en: 'Makes AI-written code production-safe by catching the most common AI hallucinations before merge.',
    },
    businessValue: {
      zh: '适用于使用 AI 编程的团队/企业，作为 CI 流程中的质量门禁，降低 AI 代码引入生产环境的风险。',
      en: 'CI quality gate for teams using AI coding — reduces risk of AI-generated code in production.',
    },
    highlights: { zh: ['11+ 检测器', '13 语言', '本地零成本', 'CI 集成'], en: ['11+ detectors', '13 langs', 'local & free', 'CI-ready'] },
    repo: 'https://github.com/ldkong2077/aide',
    demo: '',
    status: 'open',
    original: true,
    motif: 'terminal',
    accent: '#2563eb',
  },

  {
    id: 'solo',
    name: { zh: 'Solo · 中文 AI 编程 Agent', en: 'Solo · Chinese AI Coding Agent' },
    tagline: { zh: '面向中国独立开发者的 Rust 版 AI Coding Agent CLI', en: 'A Rust-based AI coding agent CLI for Chinese indie developers' },
    cat: 'ai-dev',
    tech: ['Rust', 'Cargo', 'CLI', 'AES-256-GCM', '上下文压缩'],
    desc: {
      zh: '多模型智能路由的 AI 编程 Agent：简单任务用便宜模型、复杂任务用强模型，内置代码安全审查与长会话上下文压缩。',
      en: 'A multi-model AI coding agent with cost-aware routing, built-in static safety review and long-session context compression.',
    },
    depth: {
      zh: ['多模型智能路由（DeepSeek/Qwen/MiniMax/GLM/Ollama），按复杂度自动选最优模型',
           '成本优化：简单任务走低造价模型，自动降低 API 调用成本',
           '内置代码安全审查（guardrails），零 API 成本静态分析',
           '会话持久化 + 上下文自动压缩；AES-256-GCM 加密存储 API Key'],
      en: ['Cost-aware multi-model routing (DeepSeek/Qwen/MiniMax/GLM/Ollama)',
           'Automatic cost optimization by task complexity',
           'Built-in static code safety review (guardrails), zero API cost',
           'Session persistence + context compression; AES-256-GCM key storage'],
    },
    value: {
      zh: '把「昂贵的全能模型」拆成「按需调度」，让独立开发者用更低成本跑通 Chat↔工具调用的完整编程闭环。',
      en: 'Lets indie developers run a full coding loop at lower cost via on-demand model scheduling.',
    },
    businessValue: {
      zh: '面向中国独立开发者市场，降低 AI 编程工具的使用成本，可进一步发展为商业化 AI 编程助手产品。',
      en: 'Targets the Chinese indie developer market — potential to evolve into a commercial AI coding assistant.',
    },
    highlights: { zh: ['Rust 构建', '成本路由', '安全审查', '中文原生'], en: ['Rust', 'cost routing', 'safety review', 'CN-native'] },
    repo: 'https://github.com/ldkong2077/solo',
    demo: '',
    status: 'open',
    original: true,
    motif: 'terminal',
    accent: '#7c3aed',
  },

  {
    id: 'contract-comparator',
    name: { zh: '合同扫描件比对引擎', en: 'Contract Comparator' },
    tagline: { zh: '字段级 OCR 比对 · Excel 差异 · LLM 语义评估', en: 'Field-level OCR diff · Excel delta · LLM semantic eval' },
    cat: 'ai-app',
    tech: ['Python', 'RapidOCR/EasyOCR/Tesseract', 'FastAPI', 'Streamlit', 'LLM'],
    desc: {
      zh: '面向法务/财务/审计的文档智能比对系统：把盖章合同扫描件与原始 Word/Excel 比对，自动指出哪里被改了。',
      en: 'A document-intelligence comparison engine for legal/finance/audit that diffs signed scans against original Word/Excel.',
    },
    depth: {
      zh: ['多引擎 OCR 编排（RapidOCR→EasyOCR→Tesseract 自动降级）+ OpenCV 图像预处理',
           '字段级抽取 13+ 类要素（金额/日期/合同号/主体），支持中文大写金额解析',
           '三合一界面：CLI / Streamlit Web / FastAPI REST（25 个端点）',
           'Excel 单元格级差异 + 行增删检测 + 多 Sheet；LLM 双模型交叉语义评估',
           '安全层：HMAC-SHA256 认证、RBAC、SQLite WAL + Fernet 加密、审计日志'],
      en: ['Multi-engine OCR orchestration with auto-fallback + OpenCV preprocessing',
           'Field extraction for 13+ elements (amounts/dates/parties), CN-capital parsing',
           'Three UIs: CLI / Streamlit / FastAPI REST (25 endpoints)',
           'Cell-level Excel diff + row add/delete detection; dual-LLM semantic eval',
           'Security: HMAC-SHA256, RBAC, SQLite WAL + Fernet, audit log'],
    },
    value: {
      zh: '把原本数小时的纸质合同人工复核压缩到分钟级，且本地优先、可内网部署，满足合规与数据安全要求。',
      en: 'Cuts hours of manual contract review to minutes, with a local-first design for compliance.',
    },
    businessValue: {
      zh: '可直接面向律所、审计事务所、企业法务部销售，SaaS 或本地部署模式均可，市场刚需且付费意愿强。',
      en: 'Directly marketable to law firms, audit firms, and corporate legal departments — strong willingness to pay.',
    },
    highlights: { zh: ['字段级 OCR', '三合一 UI', 'LLM 语义', '企业级安全'], en: ['field OCR', '3 UIs', 'LLM eval', 'enterprise sec'] },
    repo: 'https://github.com/ldkong2077/contract-comparator',
    demo: '',
    status: 'open',
    original: true,
    motif: 'diff',
    accent: '#0891b2',
  },

  {
    id: 'copywriting-workbench',
    name: { zh: '文案工作台', en: 'Copywriting Workbench' },
    tagline: { zh: '多模型并行 · 交叉验证 · 择优融合', en: 'Multi-model · cross-validation · fusion' },
    cat: 'ai-app',
    tech: ['Python', 'Flask', 'Ollama', 'Multi-LLM', 'Docker'],
    desc: {
      zh: '面向中文场景的多模型 AI 文案审核与生成系统：多个模型并行写作、双模型交叉审核、择优融合。',
      en: 'A Chinese-first multi-model copywriting system: parallel generation, dual-model cross-review, fusion.',
    },
    depth: {
      zh: ['多模型并行生成（2–4 个模型同时写，对比选优）',
           '双模型交叉验证审核：10 大维度（AI 味/错别字/逻辑/风格…）+ 7+ 场景模板',
           '融合推荐：从多版本提取最佳片段融合为一篇',
           'BYOK 隐私：API Key 仅存浏览器 localStorage，服务端不持久化',
           '离线模式 ONLY_LOCAL_MODE：拦截所有云端请求，仅用本地 Ollama'],
      en: ['Parallel generation across 2–4 models',
           'Dual-model cross-validation: 10 review dimensions + 7+ scene templates',
           'Fusion: merge best fragments from multiple versions',
           'BYOK privacy: keys only in browser localStorage',
           'Offline mode: blocks cloud calls, local Ollama only'],
    },
    value: {
      zh: '用「多模型交叉验证」降低单一大模型盲区，适合政务、金融、医疗等容错率低的正式文案生产。',
      en: 'Reduces single-model blind spots via cross-validation — fit for government/finance/medical copy.',
    },
    businessValue: {
      zh: '面向企业市场部、政务宣传部门、金融机构的内容审核场景，可私有化部署，数据安全合规。',
      en: 'Targets corporate marketing, government communications, and financial content review — private deployment for compliance.',
    },
    highlights: { zh: ['多模型并行', '交叉验证', 'BYOK 隐私', '本地部署'], en: ['parallel', 'cross-review', 'BYOK', 'local'] },
    repo: 'https://github.com/ldkong2077/copywriting-workbench',
    demo: '',
    status: 'open',
    original: true,
    motif: 'chat',
    accent: '#db2777',
  },

  {
    id: 'suiji',
    name: { zh: '随记 Suiji · 个人记忆 OS', en: 'Suiji · Personal Memory OS' },
    tagline: { zh: '本地优先的数字记忆操作系统', en: 'Local-first personal digital memory OS' },
    cat: 'ai-app',
    tech: ['FastAPI', 'React', 'TypeScript', 'SQLAlchemy', 'ChromaDB', 'LiteLLM'],
    desc: {
      zh: '把你日常的记录、消费、待办与对话沉淀为可检索的长期记忆，并用大模型提供智能回复与自动结构化。',
      en: 'Turns daily notes, spending, todos and chats into searchable long-term memory with LLM structuring.',
    },
    depth: {
      zh: ['后端 FastAPI + SQLAlchemy（SQLite/aiosqlite）+ Alembic 自动迁移',
           '前端 React + TypeScript + Vite，由后端同源托管（SPA）',
           '向量检索 chromadb + sentence-transformers（本地可选增强）',
           '基于 litellm 的多供应商接入；可选 iLink 微信长连接适配器',
           '本地鉴权（Fernet 加密 API Key）、SSRF 防护、数据默认只存本机'],
      en: ['Backend FastAPI + SQLAlchemy (SQLite/aiosqlite) + Alembic migrations',
           'Frontend React + TypeScript + Vite, same-origin SPA hosting',
           'Vector search via chromadb + sentence-transformers (optional local)',
           'litellm multi-provider; optional iLink WeChat adapter',
           'Local auth (Fernet), SSRF guard, data stays on-device'],
    },
    value: {
      zh: '一个真正「数据不出本机」的个人知识底座，把碎片记录自动结构化，是 AI 助理的本地化范式实践。',
      en: 'A truly on-device memory base that structures fragmented notes — a local-first AI assistant pattern.',
    },
    businessValue: {
      zh: '可作为个人知识管理（PKM）工具的差异化产品，隐私保护是核心卖点，适合安全敏感型企业客户。',
      en: 'A differentiated PKM tool with privacy as the core selling point — ideal for security-conscious enterprise clients.',
    },
    highlights: { zh: ['本地优先', '向量记忆', '多模型', '微信接入'], en: ['local-first', 'vector mem', 'multi-LLM', 'WeChat'] },
    repo: 'https://github.com/ldkong2077/suiji',
    demo: '',
    status: 'open',
    original: true,
    motif: 'memory',
    accent: '#16a34a',
  },

  {
    id: 'codex-gateway',
    name: { zh: 'codex-gateway · 模型网关', en: 'codex-gateway' },
    tagline: { zh: '把 Codex Responses API 转接到任意兼容网关', en: 'Bridge Codex Responses API to any OpenAI-compatible provider' },
    cat: 'infra',
    tech: ['Python', 'FastAPI', 'Responses API', 'Chat Completions', 'Docker'],
    desc: {
      zh: '轻量本地网关：接收 Codex 风格的 Responses API 请求，转发到 DeepSeek/GLM/Qwen/Ollama 等 OpenAI 兼容后端。',
      en: 'A lightweight local gateway that forwards Codex-style Responses API to OpenAI-compatible backends.',
    },
    depth: {
      zh: ['Responses API ↔ Chat Completions 请求/响应双向转换',
           '供应商专用适配器（DeepSeek/GLM/MiniMax/Kimi/Qwen/Ollama/LM Studio/Jan）',
           'Web UI 管理模型端点、API Key、系统提示词与当前模型',
           '可选网关鉴权；绑定 0.0.0.0 强制要求 GATEWAY_AUTH_TOKEN（防公网暴露）'],
      en: ['Bidirectional Responses API ↔ Chat Completions conversion',
           'Provider-specific adapters (DeepSeek/GLM/MiniMax/Kimi/Qwen/Ollama…)',
           'Web UI for endpoints, keys, system prompts, active model',
           'Optional auth; public bind requires token (anti-exposure guard)'],
    },
    value: {
      zh: '让只认 OpenAI 协议的 Coding Agent（如 Codex）无缝用上国产/本地模型，降低对单一厂商的依赖。',
      en: 'Lets OpenAI-only coding agents (e.g. Codex) use domestic/local models, avoiding vendor lock-in.',
    },
    businessValue: {
      zh: '面向使用 AI 编程工具的企业，需要国产模型替代方案时，作为轻量级网关中间件，降低迁移成本。',
      en: 'Middleware for enterprises needing domestic model alternatives for AI coding tools — reduces migration cost.',
    },
    highlights: { zh: ['协议转换', '多供应商', 'Web 管理', '安全护栏'], en: ['protocol bridge', 'multi-provider', 'web UI', 'safe guard'] },
    repo: 'https://github.com/ldkong2077/codex-gateway',
    demo: '',
    status: 'open',
    original: true,
    motif: 'network',
    accent: '#ea580c',
  },

  {
    id: 'one-api-hub',
    name: { zh: '大模型聚合站（私有化部署）', en: 'LLM Hub (Private Deployment)' },
    tagline: { zh: '基于 One-API 的大模型聚合/分发网关', en: 'One-API based LLM aggregation gateway' },
    cat: 'infra',
    tech: ['Go', 'One-API (fork)', 'Docker', '多模型分发'],
    desc: {
      zh: '基于开源项目 One-API 的大模型聚合与分发网关的私有化部署与适配（非从零自研）。',
      en: 'A private deployment & adaptation of the open-source One-API LLM gateway (not built from scratch).',
    },
    depth: {
      zh: ['基于 One-API（Go）进行私有化部署与配置适配',
           '统一 API 入口聚合多家大模型供应商，集中配额与密钥管理',
           'Docker 化部署，便于在内网/自有服务器上运行'],
      en: ['Private deployment & config adaptation on top of One-API (Go)',
           'Unified API entry aggregating multiple LLM vendors with central quota/key mgmt',
           'Dockerized for intranet / self-hosted runs'],
    },
    value: {
      zh: '体现「部署与运维复杂 AI 基础设施」的工程能力：把社区成熟方案落地为可控、可审计的私有服务。',
      en: 'Demonstrates the ability to deploy & operate complex AI infra as a controlled, auditable private service.',
    },
    businessValue: {
      zh: '面向需要统一管理多个大模型 API 的企业，降低 API 管理复杂度，控制成本与配额。',
      en: 'For enterprises that need unified LLM API management — reduces complexity, controls costs and quotas.',
    },
    highlights: { zh: ['One-API 二次部署', '统一分发', '私有化'], en: ['One-API fork', 'unified routing', 'self-hosted'] },
    repo: '',
    demo: '',
    status: 'deploy',
    original: false,
    motif: 'network',
    accent: '#ca8a04',
  },

  {
    id: 'real-estate-calc',
    name: { zh: '房地产项目经济测算工具', en: 'Real Estate Econ. Calculator' },
    tagline: { zh: '双口径财务 · 土增税超率累进 · 敏感性分析', en: 'Dual-base finance · LAT · sensitivity' },
    cat: 'industry',
    tech: ['原生 JavaScript', 'ECharts', '财务建模', '单文件离线'],
    desc: {
      zh: '基于利益统筹模型的房地产项目经济测算工具：投资估算、销售预测、双口径财务分析、税务计算与敏感性分析。',
      en: 'A real-estate project econometric tool: investment, sales, dual-base finance, tax and sensitivity analysis.',
    },
    depth: {
      zh: ['财务分析：全投资/权益双口径 MIRR、IRR、NPV、ROI、ROE、回收期、月度现金流',
           '税务：增值税（一般/简易，含预缴清算）、土地增值税四级超率累进、企业所得税',
           '敏感性分析：售价/成本/地价/利率波动 + 盈亏平衡安全边际',
           '深圳专项：五因子地价系数模型（建筑类型/年期/产权/楼层/项目修正）',
           '14 个引擎模块、74 项测试；可打包为单文件离线 HTML'],
      en: ['Finance: all-invest / equity dual-base MIRR, IRR, NPV, ROI, ROE, payback, monthly cashflow',
           'Tax: VAT (general/simple, with prepay & settlement), LAT 4-tier progressive, CIT',
           'Sensitivity: price/cost/land/rate variance + breakeven safety margin',
           'SZ-specific: 5-factor land-price coefficient model',
           '14 engine modules, 74 tests; single-file offline HTML build'],
    },
    value: {
      zh: '把地产投拓最核心的「算账」能力做成可分发、可审计的工具，双口径与土增税模型直接对标实务口径。',
      en: 'Packages core real-estate underwriting into an auditable, distributable tool aligned with practice.',
    },
    businessValue: {
      zh: '面向地产开发商、投资机构、咨询公司的投拓部门，可替代手动 Excel 测算，提升精度与效率。',
      en: 'For real estate developers, investment firms, and consultancies — replaces manual Excel modeling.',
    },
    highlights: { zh: ['双口径 IRR', '土增税累进', '敏感性', '深圳五因子'], en: ['dual IRR', 'LAT progressive', 'sensitivity', 'SZ 5-factor'] },
    repo: 'https://github.com/ldkong2077/real-estate-calc',
    demo: '',
    status: 'open',
    original: true,
    motif: 'calculator',
    accent: '#0d9488',
  },

  {
    id: 'renewal-flow',
    name: { zh: '拆迁云 · 城市更新管理系统', en: 'Renewal-Flow' },
    tagline: { zh: '生产级城市更新与土地整备项目管理系统', en: 'Production urban-renewal project management' },
    cat: 'industry',
    tech: ['Node.js', 'Express', 'Prisma', 'PostgreSQL', 'Vue'],
    desc: {
      zh: '城市更新/土地整备项目的生产级管理系统：涵盖项目、资金、放款、权限与审计的完整业务闭环。',
      en: 'A production-grade management system for urban-renewal / land-consolidation projects end-to-end.',
    },
    depth: {
      zh: ['金额全程使用 Prisma.Decimal，无浮点误差；事务 Serializable 隔离',
           '无原始 SQL 拼接（仅参数化健康检查），无硬编码密钥/内网 IP',
           '敏感字段加密落库（encryptSensitiveFields）、软删除注入 deletedAt',
           '安全基线：helmet、限流、trust proxy 修正、审计日志；含 SECURITY.md / COMMERCIAL_* 文档',
           'docker-compose + Caddy/nginx 一键部署，经生产级上线终审'],
      en: ['Money uses Prisma.Decimal (no float error); Serializable transactions',
           'No raw SQL concat; no hardcoded secrets / intranet IPs',
           'Sensitive-field encryption at rest; soft-delete via deletedAt',
           'Security baseline: helmet, rate-limit, trust-proxy fix, audit log; SECURITY.md docs',
           'docker-compose + Caddy/nginx one-click; passed production launch audit'],
    },
    value: {
      zh: '把城市更新这类强业务、强合规场景做成可上线的系统，体现从业务建模到生产部署的完整工程能力。',
      en: 'Ships a compliance-heavy urban-renewal system — full capability from domain modeling to production.',
    },
    businessValue: {
      zh: '面向城市更新/拆迁管理企业，SaaS 或私有化部署，市场空间大，行业壁垒高，有长期商业价值。',
      en: 'For urban renewal / demolition management enterprises — large market, high entry barrier, long-term value.',
    },
    highlights: { zh: ['生产级', 'Decimal 无误差', '加密/审计', '一键部署'], en: ['production', 'Decimal-safe', 'encrypt/audit', '1-click deploy'] },
    repo: 'https://github.com/ldkong2077/renewal-flow',
    demo: '',
    status: 'open',
    original: true,
    motif: 'map',
    accent: '#9333ea',
  },

  {
    id: 'stock-selector',
    name: { zh: '选股决策系统 v2.0', en: 'Stock Selector v2.0' },
    tagline: { zh: '14 策略融合 · 市场动态加权 · 多源容灾', en: '14-strategy fusion · dynamic weighting' },
    cat: 'fintech',
    tech: ['Python', 'pandas', 'NumPy', 'AKShare', '回测'],
    desc: {
      zh: 'A 股个人研究用选股决策工具：基于 14 个量化策略多因子打分，并结合市场环境动态加权给出买点建议。',
      en: 'A personal A-share stock-selection tool: 14 quant strategies fused with market-phase dynamic weighting.',
    },
    depth: {
      zh: ['14 个策略融合（龙回头/RPS 动量/尾盘低吸/突破/龙头战法/北向追踪…）',
           '动态市场加权：攻击/蓄力/调整/震荡/熊市期自动调权',
           '多数据源容灾：东方财富/AKShare/腾讯/新浪自动切换 + 重试熔断',
           '风险控制：移动止损、仓位管理、T+1、涨跌停检测；Web 看板 + 回测 + 绩效跟踪',
           'watchlist AES 加密存储；含 systemd / Supervisor / Docker 部署'],
      en: ['14 fused strategies (dragon-callback / RPS / tail-buy / breakout / leader / north-flow…)',
           'Dynamic market-phase weighting (attack/accumulate/adjust/shake/bear)',
           'Multi-source fault tolerance (Eastmoney/AKShare/Tencent/Sina) + retry/circuit-breaker',
           'Risk: trailing stop, position sizing, T+1, limit guards; Web board + backtest + perf',
           'AES-encrypted watchlist; systemd / Supervisor / Docker deploy'],
    },
    value: {
      zh: '把主观的「看盘经验」沉淀为可回测、可复盘的量化框架，并强调容灾与风控而非盲目追涨。',
      en: 'Turns discretionary "tape-reading" into a backtestable, risk-aware quant framework.',
    },
    businessValue: {
      zh: '可作为个人投资者的量化投研平台，也可扩展为面向私募/机构的投研辅助工具。',
      en: 'A quant research platform for individual investors, extensible to institutional-grade research tools.',
    },
    highlights: { zh: ['14 策略', '动态加权', '多源容灾', '回测'], en: ['14 strategies', 'dyn. weight', 'multi-source', 'backtest'] },
    repo: 'https://github.com/ldkong2077/stock-selector',
    demo: '',
    status: 'open',
    original: true,
    motif: 'chart',
    accent: '#dc2626',
  },

  {
    id: 'keyword-filter',
    name: { zh: '关键词筛选助手', en: 'Keyword Filter Assistant' },
    tagline: { zh: '跨平台关键词高亮 · 筛选 · 聚合', en: 'Cross-platform keyword highlight & aggregate' },
    cat: 'efficiency',
    tech: ['Tampermonkey', 'JavaScript', 'GM API', 'MutationObserver'],
    desc: {
      zh: '油猴脚本 + 链接发射台：在微博/抖音/B站/小红书/百度贴吧搜索页按关键词高亮、筛选并跨平台聚合命中帖子。',
      en: 'A Tampermonkey script + launcher that highlights, filters and cross-aggregates keyword hits across platforms.',
    },
    depth: {
      zh: ['跨 5 平台自动注入筛选面板；布尔查询（AND / OR / 排除）',
           '匹配范围可调（标题/标题+作者/标题+正文）；页面内高亮 + 非命中压暗',
           '跨标签聚合看板：基于 GM_setValue 在多标签页间共享去重命中',
           'SPA 友好：MutationObserver 监听 DOM 自动重扫，含选择器失效兜底'],
      en: ['Auto-injected panel on 5 platforms; boolean query (AND / OR / exclude)',
           'Adjustable scope (title / title+author / title+body); in-page highlight + dim',
           'Cross-tab aggregate board via GM_setValue (dedup across tabs)',
           'SPA-friendly: MutationObserver auto-rescan with selector fallback'],
    },
    value: {
      zh: '做内容选题、竞品监控、招商获客时，把「各平台手动刷关键词」变成一键聚合的可视化看板。',
      en: 'Turns manual per-platform keyword scanning into a one-click aggregated board for ops/competitor monitoring.',
    },
    businessValue: {
      zh: '面向新媒体运营、品牌公关、市场调研团队，可发展为跨平台舆情监控 SaaS 工具。',
      en: 'For social media ops, PR, and market research teams — potential SaaS cross-platform monitoring tool.',
    },
    highlights: { zh: ['5 平台', '布尔查询', '跨标签聚合', 'SPA 友好'], en: ['5 platforms', 'boolean', 'cross-tab', 'SPA-safe'] },
    repo: 'https://github.com/ldkong2077/keyword-filter',
    demo: '',
    status: 'open',
    original: true,
    motif: 'grid',
    accent: '#2563eb',
  },

  {
    id: 'search-link-gen',
    name: { zh: '搜索链接生成器', en: 'Search Link Generator' },
    tagline: { zh: '16 平台批量搜索链接 · 零依赖离线', en: '16-platform batch search links · zero-dep' },
    cat: 'efficiency',
    tech: ['原生 HTML', 'CSS', 'JavaScript', '零依赖', '响应式'],
    desc: {
      zh: '纯前端、零依赖的搜索链接批量生成器：覆盖 16 个社媒与电商平台，PC/移动端自适应。',
      en: 'A zero-dependency static tool that batch-generates search links across 16 social & e-commerce platforms.',
    },
    depth: {
      zh: ['16 个平台（微博/抖音/小红书/微信/知乎/京东/淘宝…）覆盖社媒与电商',
           '批量打开（5/10/15/20 每批），避免一次性打开过多标签页卡顿',
           'PC/移动端自适应链接；关键词模板本地保存；深色模式 & 响应式',
           '纯本地运行，无需后端、无需联网、不收集任何数据'],
      en: ['16 platforms (Weibo/Douyin/Xiaohongshu/WeChat/Zhihu/JD/Taobao…)',
           'Batch-open (5/10/15/20 per batch) to avoid tab flooding',
           'PC/mobile-adaptive links; local keyword templates; dark mode & responsive',
           'Pure local: no backend, no network, no data collection'],
    },
    value: {
      zh: '舆情监控、竞品分析、品牌追踪时，把「逐个平台手拼搜索 URL」变成一键批量生成。',
      en: 'For PR/competitor/brand monitoring, replaces manual per-platform URL crafting with one-click batch gen.',
    },
    businessValue: {
      zh: '运营人员的实用效率工具，可发展为浏览器扩展或团队协作工具，轻量级但高频使用场景。',
      en: 'A practical productivity tool for ops — potential browser extension or team collaboration tool.',
    },
    highlights: { zh: ['16 平台', '批量打开', '零依赖', '响应式'], en: ['16 platforms', 'batch open', 'zero-dep', 'responsive'] },
    repo: 'https://github.com/ldkong2077/search-link-generator',
    demo: '',
    status: 'open',
    original: true,
    motif: 'grid',
    accent: '#0891b2',
  },

  {
    id: 'toolhub',
    name: { zh: 'ToolHub · 一站式工具集合', en: 'ToolHub' },
    tagline: { zh: 'AI 助手 / 文档 / 设计 / 行业工具聚合导航', en: 'Aggregated navigator for AI/docs/design/tools' },
    cat: 'efficiency',
    tech: ['Next.js 16', 'React 19', 'TypeScript', 'Tailwind CSS', 'Docker'],
    desc: {
      zh: '聚合 AI 助手、文档处理、设计媒体、协作通讯、行业与开发工具的一站式导航站，静态导出、可离线复现。',
      en: 'A one-stop navigator aggregating AI assistants, docs, design, collaboration and dev tools; static-export, offline-reproducible.',
    },
    depth: {
      zh: ['二级分类导航 + 智能搜索（名称/拼音首字母/标签/场景多维度）',
           '收藏常用（最多 12）+ 最近使用（8）；工具详情抽屉 + 相关推荐',
           '亮/暗/跟随系统三主题，偏好持久化无闪烁；键盘快捷键（/ 聚焦、Esc 关闭）',
           '纯静态导出（output: export），零外部构建依赖；Docker 多阶段构建注入 CSP 等安全头'],
      en: ['Two-level category nav + smart search (name/pinyin/tag/scenario)',
           'Favorites (≤12) + recents (8); detail drawer + recommendations',
           'Light/Dark/System themes, persistence w/o flicker; hotkeys (/ focus, Esc close)',
           'Pure static export; zero external build deps; Docker multi-stage injects CSP etc.'],
    },
    value: {
      zh: '解决「在无数来源间反复找工具」的痛点，把分散的提效工具收敛到一个可被搜索的入口。',
      en: 'Converges scattered productivity tools into one searchable entry point.',
    },
    businessValue: {
      zh: '可作为企业内部门户/工具导航站，也可发展为面向特定行业的工具聚合平台，有广告/推广变现潜力。',
      en: 'Enterprise internal tool portal or industry-specific tool aggregator — potential for ad/sponsorship revenue.',
    },
    highlights: { zh: ['二级分类', '拼音搜索', '收藏/最近', '纯静态'], en: ['2-level nav', 'pinyin search', 'fav/recents', 'static'] },
    repo: 'https://github.com/ldkong2077/toolhub',
    demo: '',
    status: 'open',
    original: true,
    motif: 'grid',
    accent: '#7c3aed',
  },

  {
    id: 'numboxhub',
    name: { zh: 'NumBoxHub · 国际薪资计算器', en: 'NumBoxHub' },
    tagline: { zh: '隐私优先的国际薪资 / 税务 / 按揭计算器', en: 'Privacy-first intl salary/tax/mortgage calculators' },
    cat: 'efficiency',
    tech: ['静态多页', 'HTML', 'CSS', 'JavaScript', '多语言'],
    desc: {
      zh: '已上线的多语言在线计算器站：美国薪资税务、德国 Brutto/Netto、时薪换算、按揭等，隐私优先。',
      en: 'A live multilingual calculator site: US salary/tax, German Brutto/Netto, hourly conversion, mortgage — privacy-first.',
    },
    depth: {
      zh: ['多语言（美/德等）薪资、税务、时薪、资本利得计算器',
           '隐私优先：纯静态、无后端追踪；首页即时粗略估算无需跳转',
           '清晰标注本地税率假设，按年度税政更新',
           '静态多页架构（index/about/contact/guides/tools…），利于 SEO 与托管'],
      en: ['Multilingual salary/tax/hourly/capital-gains calculators (US/DE…)',
           'Privacy-first: pure static, no backend tracking; instant on-page estimate',
           'Clearly stated local tax assumptions, updated per annual rules',
           'Static multi-page architecture (index/about/contact/guides/tools…) for SEO'],
    },
    value: {
      zh: '面向全球职场人的实用工具站，已真实上线运行，体现「从产品定义到上线运营」的闭环能力。',
      en: 'A real, live product for global professionals — demonstrates product-definition-to-launch capability.',
    },
    businessValue: {
      zh: '面向全球职场人群的工具站，可接入广告联盟或提供高级功能订阅，已上线运营有真实流量基础。',
      en: 'A live tool site for global professionals — potential for ad revenue or premium subscriptions.',
    },
    highlights: { zh: ['已上线', '多语言', '隐私优先', '税务精准'], en: ['live', 'multilingual', 'privacy', 'tax-accurate'] },
    repo: 'https://github.com/ldkong2077/numboxhub',
    demo: '',
    status: 'open',
    original: true,
    motif: 'calculator',
    accent: '#0d9488',
  },
];

// 供 app.js 使用
if (typeof window !== 'undefined') {
  window.CATEGORIES = CATEGORIES;
  window.PROJECTS = PROJECTS;
}